# Generated by Django 6.0.4 on 2026-05-11 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Repas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('heure_repas', models.TimeField()),
                ('age_minimum_mois', models.IntegerField()),
                ('cout_estime_fcfa', models.FloatField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aliment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('age_minimum_mois', models.IntegerField()),
                ('valeur_nutritive', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='aliments/')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profil.region')),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nutrition.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.FloatField()),
                ('unite', models.CharField(max_length=50)),
                ('aliment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.aliment')),
                ('repas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.repas')),
            ],
        ),
    ]
