# Generated by Django 6.0.5 on 2026-05-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliment',
            name='prix_unitaire_fcfa',
            field=models.FloatField(default=0.0),
        ),
    ]
