# Generated by Django 6.0.5 on 2026-05-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_aliment_prix_unitaire_fcfa'),
    ]

    operations = [
        migrations.AddField(
            model_name='repas',
            name='recette',
            field=models.TextField(blank=True),
        ),
    ]
