# Generated by Django 6.0.5 on 2026-05-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_repas_recette'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliment',
            name='allergenes',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
