# Generated by Django 6.0.4 on 2026-05-28 09:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0004_aliment_allergenes'),
        ('profil', '0002_allergie_allergibebe'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepasProgramme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('heure', models.TimeField()),
                ('active_alarm', models.BooleanField(default=True)),
                ('notification_envoyee', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bebe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repas_programmes', to='profil.bebe')),
                ('repas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmations', to='nutrition.repas')),
            ],
            options={
                'verbose_name': 'Repas programmé',
                'verbose_name_plural': 'Repas programmés',
                'ordering': ['date', 'heure'],
                'unique_together': {('bebe', 'repas', 'date', 'heure')},
            },
        ),
    ]
