# Generated by Django 6.0.5 on 2026-06-03 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0005_repasprogramme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repas',
            name='heure_repas',
        ),
        migrations.CreateModel(
            name='HoraireRepas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure', models.TimeField()),
                ('repas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to='nutrition.repas')),
            ],
        ),
    ]
