# Generated by Django 6.0.4 on 2026-06-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0006_remove_repas_heure_repas_horairerepas'),
    ]

    operations = [
        migrations.AddField(
            model_name='repas',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='repas/'),
        ),
    ]
