# Generated by Django 6.0.4 on 2026-06-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0007_repas_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repas',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='repas/'),
        ),
    ]
