// /** @type {import('tailwindcss').Config} */
// export default {
//   content: [
//     "./index.html",
//     "./src/**/*.{js,ts,jsx,tsx}",
//   ],
//   theme: {
//     extend: {
//       colors: {
//         "primary": "#0f5238",
//         "primary-container": "#2d6a4f",
//         "secondary-container": "#ffab69",
//         "surface": "#f8f9fa",
//         "background": "#f8f9fa",
//         "on-background": "#191c1d",
//         "on-surface-variant": "#404943",
//         "outline-variant": "#bfc9c1",
//         "secondary-fixed": "#ffdcc4",
//         "on-secondary-fixed-variant": "#6f3800",
//         "primary-fixed": "#b1f0ce",
//         "on-primary-fixed-variant": "#0e5138",
//       }
//     },
//   },
//   plugins: [],
// }

export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#0f5238",
        "on-primary": "#ffffff",
        "primary-container": "#2d6a4f",
        "on-primary-container": "#a8e7c5",
        "primary-fixed": "#b1f0ce",
        "primary-fixed-dim": "#95d4b3",
        "on-primary-fixed": "#002114",
        "on-primary-fixed-variant": "#0e5138",
        "secondary": "#8e4e14",
        "on-secondary": "#ffffff",
        "secondary-container": "#ffab69",
        "on-secondary-container": "#783d01",
        "secondary-fixed": "#ffdcc4",
        "secondary-fixed-dim": "#ffb780",
        "on-secondary-fixed": "#2f1400",
        "on-secondary-fixed-variant": "#6f3800",
        "tertiary": "#004b77",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#1e6396",
        "on-tertiary-container": "#bdddff",
        "tertiary-fixed": "#cee5ff",
        "tertiary-fixed-dim": "#97cbff",
        "on-tertiary-fixed": "#001d33",
        "on-tertiary-fixed-variant": "#004a76",
        "surface": "#f8f9fa",
        "surface-dim": "#d9dadb",
        "surface-bright": "#f8f9fa",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f4f5",
        "surface-container": "#edeeef",
        "surface-container-high": "#e7e8e9",
        "surface-container-highest": "#e1e3e4",
        "surface-variant": "#e1e3e4",
        "surface-tint": "#2c694e",
        "on-surface": "#191c1d",
        "on-surface-variant": "#404943",
        "background": "#f8f9fa",
        "on-background": "#191c1d",
        "outline": "#707973",
        "outline-variant": "#bfc9c1",
        "inverse-surface": "#2e3132",
        "inverse-on-surface": "#f0f1f2",
        "inverse-primary": "#95d4b3",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        "body-md": ["Atkinson Hyperlegible Next", "sans-serif"],
        "headline-xl": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Atkinson Hyperlegible Next", "sans-serif"],
        "label-sm": ["Atkinson Hyperlegible Next", "sans-serif"],
        "body-lg": ["Atkinson Hyperlegible Next", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-xl": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
      spacing: {
        "margin-mobile": "1rem",
        "margin-desktop": "2.5rem",
        "stack-sm": "0.5rem",
        "stack-md": "1.5rem",
        "stack-lg": "2.5rem",
        "gutter": "1rem",
        "base": "8px",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
}

module.exports = {
  theme: {
    extend: {
      colors: {
        primary: '#0f5238',
        terracotta: '#d47a5a',
      },
    },
  },
};