# Generated by Django 6.0.4 on 2026-05-11 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mesure', models.DateField()),
                ('poids', models.FloatField()),
                ('taille', models.FloatField()),
                ('age_en_mois', models.IntegerField()),
                ('bebe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profil.bebe')),
            ],
        ),
    ]
