# Generated by Django 6.0.5 on 2026-05-22 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('croissance', '0001_initial'),
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mesure',
            options={'ordering': ['-date_creation', '-date_mesure']},
        ),
        migrations.AddField(
            model_name='mesure',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='mesure',
            name='bebe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesures', to='profil.bebe'),
        ),
    ]
