# Generated by Django 6.0.5 on 2026-05-25 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('gluten', 'Gluten'), ('lactose', 'Lactose'), ('arachides', 'Arachides'), ('soja', 'Soja'), ('oeufs', 'Œufs'), ('poisson', 'Poisson'), ('fruits_mer', 'Fruits de mer'), ('noix', 'Noix'), ('autre', 'Autre')], max_length=100)),
                ('autre_precision', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AllergiBebe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_detection', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('bebe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='profil.bebe')),
                ('allergie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profil.allergie')),
            ],
        ),
    ]
