# Generated by Django 6.0.4 on 2026-05-11 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profil', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('croissance', 'Rapport de croissance'), ('nutritionnel', 'Rapport nutritionnel')], max_length=20)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='rapports/')),
                ('bebe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profil.bebe')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
