# Generated by Django 6.0.4 on 2026-05-11 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateField(auto_now_add=True)),
                ('heure_envoi', models.TimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_rdv', models.DateField(blank=True, null=True)),
                ('heure_rdv', models.TimeField(blank=True, null=True)),
                ('motif', models.TextField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('refusee', 'Refusée'), ('terminee', 'Terminée')], default='en_attente', max_length=20)),
                ('note_parent', models.FloatField(blank=True, null=True)),
                ('bebe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profil.bebe')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profil.medecin')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profil.parent')),
            ],
        ),
    ]
